/**
*
* auto generated by ibatis tools 
*
**/
package com.yc.easy.trade.domain.purchase;

import java.math.BigDecimal;

/**
* purchase_product
*/

public class PurchaseProduct  implements java.io.Serializable {

    private String productModel; //型号
    private BigDecimal num; //数量
    private String productSpecifications; //规格
    private java.util.Date updateTime; //更新时间
    private String remark; //备注
    private Integer delFlag; //删除标识。0：非删除；1：删除
    private String productName; //商品名称
    private BigDecimal totalAmount; //总金额
    private String unit; //单位
    private java.util.Date createTime; //创建时间
    private BigDecimal price; //单价
    private Integer contractId; //合同主键
    private Integer id; //主键ID，自动生成
    private String perValue; //1单位数量

    public String getProductModel (){
        return productModel;
    }
    
    public void setProductModel (String productModel){
        this.productModel = productModel;
    }
    public BigDecimal getNum (){
        return num;
    }
    
    public void setNum (BigDecimal num){
        this.num = num;
    }
    public String getProductSpecifications (){
        return productSpecifications;
    }
    
    public void setProductSpecifications (String productSpecifications){
        this.productSpecifications = productSpecifications;
    }
    public java.util.Date getUpdateTime (){
        return updateTime;
    }
    
    public void setUpdateTime (java.util.Date updateTime){
        this.updateTime = updateTime;
    }
    public String getRemark (){
        return remark;
    }
    
    public void setRemark (String remark){
        this.remark = remark;
    }
    public Integer getDelFlag (){
        return delFlag;
    }
    
    public void setDelFlag (Integer delFlag){
        this.delFlag = delFlag;
    }
    public String getProductName (){
        return productName;
    }
    
    public void setProductName (String productName){
        this.productName = productName;
    }
    public BigDecimal getTotalAmount (){
        return totalAmount;
    }
    
    public void setTotalAmount (BigDecimal totalAmount){
        this.totalAmount = totalAmount;
    }
    public String getUnit (){
        return unit;
    }
    
    public void setUnit (String unit){
        this.unit = unit;
    }
    public java.util.Date getCreateTime (){
        return createTime;
    }
    
    public void setCreateTime (java.util.Date createTime){
        this.createTime = createTime;
    }
    public BigDecimal getPrice (){
        return price;
    }
    
    public void setPrice (BigDecimal price){
        this.price = price;
    }
    public Integer getContractId (){
        return contractId;
    }
    
    public void setContractId (Integer contractId){
        this.contractId = contractId;
    }
    public Integer getId (){
        return id;
    }
    
    public void setId (Integer id){
        this.id = id;
    }
    public String getPerValue (){
        return perValue;
    }
    
    public void setPerValue (String perValue){
        this.perValue = perValue;
    }

}