/**
*
* auto generated by ibatis tools 
*
**/
package com.yc.easy.trade.domain.purchase;
/**
* purchase_product
*/

public class PurchaseProduct  implements java.io.Serializable {

    private String productModel; //型号
    private java.util.Date effectiveTime; //创建时间
    private String num; //数量
    private String productSpecifications; //规格
    private java.util.Date updateTime; //更新时间
    private String remark; //备注
    private Double delFlag; //删除标识。0：非删除；1：删除
    private String productName; //商品名称
    private java.util.Date totalAmount; //总金额
    private String unit; //单位
    private String price; //单价
    private Double contractId; //合同主键
    private Double id; //主键ID，自动生成
    private String perValue; //1单位数量

    public String getProductModel (){
        return productModel;
    }
    
    public void setProductModel (String productModel){
        this.productModel = productModel;
    }
    public java.util.Date getEffectiveTime (){
        return effectiveTime;
    }
    
    public void setEffectiveTime (java.util.Date effectiveTime){
        this.effectiveTime = effectiveTime;
    }
    public String getNum (){
        return num;
    }
    
    public void setNum (String num){
        this.num = num;
    }
    public String getProductSpecifications (){
        return productSpecifications;
    }
    
    public void setProductSpecifications (String productSpecifications){
        this.productSpecifications = productSpecifications;
    }
    public java.util.Date getUpdateTime (){
        return updateTime;
    }
    
    public void setUpdateTime (java.util.Date updateTime){
        this.updateTime = updateTime;
    }
    public String getRemark (){
        return remark;
    }
    
    public void setRemark (String remark){
        this.remark = remark;
    }
    public Double getDelFlag (){
        return delFlag;
    }
    
    public void setDelFlag (Double delFlag){
        this.delFlag = delFlag;
    }
    public String getProductName (){
        return productName;
    }
    
    public void setProductName (String productName){
        this.productName = productName;
    }
    public java.util.Date getTotalAmount (){
        return totalAmount;
    }
    
    public void setTotalAmount (java.util.Date totalAmount){
        this.totalAmount = totalAmount;
    }
    public String getUnit (){
        return unit;
    }
    
    public void setUnit (String unit){
        this.unit = unit;
    }
    public String getPrice (){
        return price;
    }
    
    public void setPrice (String price){
        this.price = price;
    }
    public Double getContractId (){
        return contractId;
    }
    
    public void setContractId (Double contractId){
        this.contractId = contractId;
    }
    public Double getId (){
        return id;
    }
    
    public void setId (Double id){
        this.id = id;
    }
    public String getPerValue (){
        return perValue;
    }
    
    public void setPerValue (String perValue){
        this.perValue = perValue;
    }

}